### ISSUE TITLE
Project-4-ForbesBillionaires

### ISSUE THREAD

**Issue by paulbancelin** [Ironhack-data-bcn-april-2023/project-IV-sql-tableau#1]
https://github.com/paulbancelin/Project-4-ForbesBillionaires

**Comment by ta-data-bcn** [comment]
Buenas Paul! 🚀🚀

Felicidades por el project!!!!!
A parte de lo que hablamos en clase, te dejo un poco de feedback.


**Respecto a la organización del repositorio** 📚

- Se te ha colado un .DS_Store, acuérdate de ponerlo dentro de tu .gitignore para que no se suban cosas innecesarias a tu repo!
- Por lo demás bien, todo limpio y en su sitio el .env si que está ignorado y no has subido ninguna contraseña al github. 👍👍

**El README.md** 📖

- El Readme ya está mucho mejor que los otros, bien estructurado, y entendible, bien también de agregar tus gráficos para que se entienda mejor tu proyecto. 
- Si que añadiría una conclusión al final dónde acabas de explicar tus resultados y así como que acabas de atar tu proyecto. 


**El código** 👩‍💻

- Ten cuidado con printear tu dataframe entero, ya que la persona que lo lee tiene que scrollear todo el rato más de 2000 celdas, cosa que lo hace menos entendible. Puedes usar .head() o .sample() para que solo salgan algunas columnas en vez de todo el dataframe. 
- Tu mismo puedes mirar en tu github que es casi imposible leer tu trabajo ya que todo el rato estás printeando el dataframe entero. 
- No tienes ninguna función :( sería bueno que lo intentaras, ya que es cómo todo el mundo está acostumbrado a verlo. 
- En general el código de python está bastante mejorable Paul
- Has hecho bien con SQL, bien utilizado la conexion y los queries! 👍👍
- Por lo demás muy bien ;)

**Visualización** 🎨

- No has hecho una parte fundamental del proyecto que era tableau! 
- De las visualizaciones que sí has hecho, están bien, enseñan lo que quieres, pero son bastante mejorables, usando plotly y metiendo más de una variable en el gráfico vas a conseguir dar más información y que se vea mejor. 


Suerte con el último Paul!!! Last push!
