### ISSUE TITLE
Final - Miguel

### ISSUE THREAD

**Issue by miguelpalospou** [Ironhack-data-bcn-april-2023/project-IV-sql-tableau#10]
https://github.com/miguelpalospou/project-IV-sql-tableau

**Comment by ta-data-bcn** [comment]
Hola Miguel!!!!!!! 🚀🚀

Felicidades por el project!!!!!
Un poco de feedback:


**Respecto a la organización del repositorio** 📚

- Se te ha colado un .DS_Store y un ipynb.checkpoints, acuérdate de ponerlo dentro de tu .gitignore para que no se suban cosas innecesarias a tu repo!
- También podrías hacer alguna carpeta para que no queden tantos documentos sueltos en tu repo principal por ejemplo los csv en una carpeta de data, las funciones 

**El README.md** 📖

- El readme está súper bien, lo único que añadiría sería un poco de explicación dentro de tus conclusiones. Aunque tus gráficas se explican por ellas solas, añadiría texto igualmente para acabar de completar la explicación


**El código** 👩‍💻

- Bien utilizadas tus funciones
- Está muy bien el hecho de que utilices celdas de markdown en tu notebook, ya que es muy fácil seguir el hilo de lo que vas haciendo
- Las queries de SQL están muy bien; me alegro de que finalmente te funcionaran las dos últimas
- Ha quedado genial que añadas tus gráficos de Tableau en el notebook de Jupiter; queda todo super explicativo y claro


**Visualización** 🎨

- No me acaba de quedar claro las gráficas de los KPI’s; faltan los datos de 2015, ¿por qué hay una bajada tan grande en el mes de julio?
- En la gráfica de los mapas, has utilizado la suma del profit margin, deberías haber utilizado el average
- Por lo demás, muy bien :)


Suerte con el último project Miguel!!! Last push!!!!!!!
