### ISSUE TITLE
Project-sql-tableau_Laura

### ISSUE THREAD

**Issue by laumosa** [Ironhack-data-bcn-april-2023/project-IV-sql-tableau#2]
https://github.com/laumosa/Project4-sql-tableau

**Comment by ta-data-bcn** [comment]
Hola Laura!!!!!!! 🚀🚀

Felicidades por el project!!!!!
Un poco de feedback:


**Respecto a la organización del repositorio** 📚

- Perfecto, nada que añadir, todo ignorado como toca :) !!!

**El README.md** 📖

- Perfecto, muy buena estructura de principio a final, explicando lo que vas a buscar y concluyendo con resultados y análisis de los resultados. 


**El código** 👩‍💻

- Muy bien tu código. Te han faltado las funciones en este project, aunque si que las veo en los notebooks te ha faltado pasarlas a la carpeta de src. 
- También muy bien las queries de SQL. Sería top poder ver también los resultados!!!!


**Visualización** 🎨

- Muy bien explicadas tus visualizaciones, me gustaría que pusieras también el link de tu Tableau para poder ver tus dashboards
- Creo que tus gráficas son interesantes, pero hay mucha info dentro de cada una. Te recomiendo por ejemplo sacar el género más usado de cada década o el director con mejor average de cada década en lugar de todos para no sobrecargar las gráficas de info

Ganas de ver tu proyecto FINAL!!!!!!!!!!!!!!!
