### ISSUE TITLE
Project 4 Ramses

### ISSUE THREAD

**Issue by RamsesMR5** [Ironhack-data-bcn-april-2023/project-IV-sql-tableau#3]
https://github.com/RamsesMR5/Project-4-.git

**Comment by ta-data-bcn** [comment]
Hola Ram!!!!!!! 🚀🚀

Felicidades por el project!!!!!
A parte de lo que vimos en clase, te dejo un poco de feedback:


**Respecto a la organización del repositorio** 📚

- Se te ha colado un .DS_Store, acuérdate de ponerlo dentro de tu .gitignore para que no se suban cosas innecesarias a tu repo!
- Por lo demás bien, todo limpio y en su sitio el .env si que está ignorado y no has subido ninguna contraseña al github. 👍👍

**El README.md** 📖

- NO HAY README, again; porfa para el final project te recomiendo que lo añadas


**El código** 👩‍💻

- Podrías añadir alguna función para acortar la parte de cleaning 
- Sobre tus queries de SQL, felicidades, están genial. Se nota que este es tu programa 


**Visualización** 🎨

- Como dijimos en clase, creo que tu Tableau está muy bien organizado; desde los boxplots hasta las diferencias entre large, medium y small. Explicas muy bien tu tema

Muy interesante tu topic. Ganas de lo que haces para el final 🙂
