### ISSUE TITLE
UFO Project

### ISSUE THREAD

**Issue by pablocabadas** [Ironhack-data-bcn-april-2023/project-IV-sql-tableau#4]
https://github.com/pablocabadas/UFO-Project.git

![giphy-18](https://github.com/Ironhack-data-bcn-april-2023/project-IV-sql-tableau/assets/127872717/829ded12-bfd2-45c0-85c4-d429072583db)

**Comment by ta-data-bcn** [comment]
Hola Pablo!!!!!!! 🚀🚀 Que susto el gif que has puesto😂😂😂😂😂

Felicidades por el project!!!!!
A parte de lo que vimos en clase, te dejo un poco de feedback:


**Respecto a la organización del repositorio** 📚

- Está perfecto; super organizado

**El README.md** 📖

- NO HAY README; porfa para el final project te recomiendo que lo añadas 


**El código** 👩‍💻

- Ten cuidado con printear tu dataframe entero, ya que la persona que lo lee tiene que scrollear todo el rato más de 2000 celdas, cosa que lo hace menos entendible. Puedes usar .head() o .sample() para que solo salgan algunas columnas en vez de todo el dataframe
- Por lo demás muy bien, Muy top la función para sacar las provincias. Solo te falta ponerlo en un doc distinto llamado src

**Visualización** 🎨

- No me has añadido el link a tu Tableau. Envíamelo cuando puedas para que le eche un vistazo
