### ISSUE TITLE
PMachado - Tableau Project IV

### ISSUE THREAD

**Issue by paulaRMachado** [Ironhack-data-bcn-april-2023/project-IV-sql-tableau#6]
https://github.com/paulaRMachado/Project-IV-Tableau-II.git

**Comment by ta-data-bcn** [comment]
Hi Paula! 🚀🚀

Congrats on your project!


**Organization of your repo** 📚

- .gitignore is working perfectly, everything is clean and tidy!


**El README.md** 📖

- It’s also really good, it’s short but straight to the point, everything that needs to be explained is explained
- Good job adding the graphs as well for better understanding. 
- I’m missing a bit the SQL side of it in the readme, like what type of queries you did and what you found through SQL

**Code** 👩‍💻

- The code is also really good, the modularization and encapsulation is done perfectly! Super easy to understand what each function does thanks to the docstrings you provide!
- Still missing the SQL part here, you didn’t do any queries? 
- Great using web scraping for the salaries data!!!!!!!!! Really like this extra point!
- Apart from this, really good, clean and simple to understand as a reader!

**Visualizations** 🎨

- I really like your visualizations as well, the map is super insightful with the option to look at different points in time, and the second graph with the dual axis also, really good! 
- I think the map for suicides could be a bit different, or maybe have had another variable.
- From what I see on the last slide of your tableau, you could conclude that people are more prone to suicide on the weekend no?
- In general, really good graphs! You have to fight a bit with tableau at the beginning but you see the cool things you can do with it!!!!!


Only one project left!!!!!!!!!!!!  You’re doing great Paula! Last push!
PD: I checked what you told me about project 3, what I meant was that you could make the API calls easier by making a function to do them for you
