### ISSUE TITLE
Leticia_Project_IV

### ISSUE THREAD

**Issue by LeticiaIruela** [Ironhack-data-bcn-april-2023/project-IV-sql-tableau#7]
https://github.com/LeticiaIruela/Project_IV

**Comment by ta-data-bcn** [comment]
LETIIII perdón por la confusión haha!
Aquí te dejo la corrección del tuyo!! Super project!

Bueeeenas LETI! 🚀🚀

Felicidades por el project!!!!!


**Respecto a la organización del repositorio** 📚

- No se te ha colado nada que no tenga que estar allí así que súper!


**El README.md** 📖

- El Readme también está muy bien, has explicado todo lo que has hecho, analizado los resultados y puesto tus conclusiones!!!!! 
- Yo de tu añadiría las gráficas más importantes también en el readme si ayudan a la comprensión de tu trabajo!!!!!

**El código** 👩‍💻

- El código está suuuuper bien!!!!! Las funciones explicadas y en su sitio :))) 
- Tu notebook también es brutal, super explicativo, las celdas de markdown a lo largo del notebook explican todo y se entiende super bien
- La funciones de SQL aunque no son muchas también están perfect!!!!!!!!!!!!!!!!!
- PROYECTAZO LETIIII!!!!!!!!! 
- Me gustaría corregirte algo más pero esque está muy muy top!

**Visualización** 🎨

- Tu Tableau también está super acertado! 
- Yo igual te recomendaría no sobrecargar los dashboards y intentar responder un punto por página! Porque alguno te ha quedado un poco como mucha info de golpe!
- A parte de esto también el Tableau te ha quedado genial!


Sigue así LETI!!!!!!!!!!!! Muchas ganas de ver lo que decides hacer para el final!!!!!!🙂
