### ISSUE TITLE
Employees and hiring team

### ISSUE THREAD

**Issue by jomape-iron** [Ironhack-data-bcn-april-2023/project-IV-sql-tableau#8]
https://public.tableau.com/app/profile/jose.mar.n/viz/Project4_16847712617600/Story1?publish=yes

**Comment by jomape-iron** [comment]
https://github.com/jomape-iron/Project_4.git

**Comment by ta-data-bcn** [comment]
Hola Jose!!!!!!! 🚀🚀

Felicidades por el project!!!!!
Un poco de feedback:


**Respecto a la organización del repositorio** 📚

- Bien utilizado el gitignore! No se te ha colado nada
- Te recomiendo hacer carpetas para guardar tus files y tenerlo todo mas organizado 
- Por lo demás todo bien 🙂

**El README.md** 📖

- El readme está súper bien, la estructura del texto hace que se entienda todo lo que estás haciendo
- Igual me faltaría ver alguno de tus gráficos aquí y unas conclusiones finales  


**El código** 👩‍💻

- Te faltan las funciones Jose!
- Veo que has usado SQL por tus exports, pero no veo tu código de SQL por ningún lado
- Por lo demás muy bien ;)

**Visualización** 🎨

- En general está bien; creo que podrías haber explorado algo más, ya que tus csv son muy detallados (ejemplo: sección, fechas exactas, causas de absentismo, y cosas en común entre los trabajadores que más se van y los que se ponen más enfermos)


Ánimos para el último project !!!!!!!!!!!
