### ISSUE TITLE
[Bego Ripoll] 

### ISSUE THREAD

**Issue by bripollc** [Ironhack-data-bcn-april-2023/project-IV-sql-tableau#9]
**Sentiment analysis extracted from booking reviews**
https://github.com/bripollc/04_Sentiment_analysis

**Comment by ta-data-bcn** [comment]
Hola Bego!!!!!!! 🚀🚀

Felicidades por el project!!!!!
Un poco de feedback:


**Respecto a la organización del repositorio** 📚

- Se te ha colado un .DS_Store, acuérdate de ponerlo dentro de tu .gitignore para que no se suban cosas innecesarias a tu repo!
- Por lo demás bien, todo limpio y en su sitio el .env si que está ignorado y no has subido ninguna contraseña al github. 👍👍

**El README.md** 📖

- El readme está súper bien, la estructura del texto y el workflow hace que se entienda todo lo que estás haciendo.
- Igual me faltaría ver un último punto de conclusiones, un poco el análisis de tus gráficos.


**El código** 👩‍💻

- Está brutal el web-scraping!!!!! Muy top. 
- Muy bien de poner todo en funciones! Solo te falta separarlas y ponerlas en una carpeta distinta. Los docstrings y comentarios también ayudan a entenderlo :)
- Por lo demás muy bien ;)

**Visualización** 🎨

- Cómo siempre te digo, súper fan de tus workflows!!!!
- Tu tableau también está super bien, me ha costado un poco entender alguna gráfica, pero después de meterme en booking entiendo que te pide una valoración positiva y una negativa. 
- En el segundo dashboard de tableau, podrías enseñar todo a la vez, o solo enseñar una gráfica que puedas ir cambiando lo años. 
- El tercero también me ha costado un poco entenderlo ya que tratas los scores como una variable continua, entonces queda como si fuera las valoraciones across time en vez de el numero de valoraciones por score.
- Por lo demás super Bego!

Ganas de ver tu final project!!!!!!!!!!
